#Docker file for creation of Helloworld and difference between RUN and CMD

FROM centos:latest
MAINTAINER sivva26@gmail.com
RUN useradd -ms /bin/bash user

CMD "echo" "This is a custom message from Siva"
USER user
